using DMCIT.Core.Entities.Core;
using DMCIT.Core.Interfaces;
using DMCIT.Core.SharedKernel;
using DMCIT.Infrastructure.Data;
using DMCIT.Utility;
using DMCIT.Web.ApiModels;
using DMCIT.Web.ApiModels.HR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DMCIT.Web.Api
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class HRController : ControllerBase
    {
        AppDbContext _context;
        ICoreRepository _coreRep;
        IRepository _repos;
        SignInManager<AppUser> _signInManager;
        UserManager<AppUser> _userManager;
        public HRController(AppDbContext context, ICoreRepository coreRep, IRepository repos, SignInManager<AppUser> signinManager, UserManager<AppUser> userManager)
        {
            _context = context;
            _coreRep = coreRep;
            _repos = repos;
            _signInManager = signinManager;
            _userManager = userManager;
        }

        async Task<AppUser> getCurrentUser()
        {
            return await _userManager.GetUserAsync(User);
        }

        #region EMPLOYEE
        [HttpPost]
        [Route("emp")]
        public async Task<IActionResult> Employees(TableParameter<EmployeeFilterModel, Employee> param)
        {
            var eParam = param.ToEntityParam();

            var list = await _coreRep.ListEmployees(eParam);
            var count = await _coreRep.GetEmployeeCount(eParam);
            return Ok(new
            BaseListModel<EmployeeModel>(list.Select(u => new EmployeeModel(u)), param.page, param.pageSize, count));
        }

        [HttpPost]
        [Route("emp/update")]
        public async Task<IActionResult> UpdateEmployee(EmployeeModel model)
        {
            var appUser = await getCurrentUser();
            var entity = model.ToEmployee();
            await _coreRep.UpdateEmployee(entity, appUser);
            return Ok(new ResponseModel(true));
        }

        [HttpPost]
        [Route("emp/delete")]
        public async Task<IActionResult> DeleteEmployees(IntCollectionModel model)
        {
            foreach (var id in model.collection)
            {
                await _coreRep.DeleteEmployee(id, await getCurrentUser());
            }
            return Ok(new ResponseModel(true));
        }

        [HttpPost]
        [Route("emp/add")]
        public async Task<IActionResult> AddEmployee(EmployeeModel model)
        {
            var entity = model.ToEmployee();
            await _coreRep.AddEmployee(entity, await getCurrentUser());
            return Ok(new ResponseModel(new { result = true }));
        }

        [HttpPost]
        [Route("emp/{id}")]
        public async Task<IActionResult> GetEmployee(int id)
        {
            var emp = await _coreRep.GetEmployeeById(id);
            if (emp != null)
            {
                return Ok(new ResponseModel(new
                EmployeeModel(emp)));
            }
            return NotFound();
        }

        [HttpPost]
        [Route("ReviewEmployeeExcel")]
        public async Task<IActionResult> ReadEmployeeExcel()
        {
            var file = Request.Form.Files[0];
            var rs = new List<EmployeeErrorableModel>();
            await FileHelper.scanExcel(file, 6, async (header, row) =>
            {
                var employee = new EmployeeErrorableModel();
                employee.person = new ApiModels.Core.PersonModel();
                try
                {
                    for (var i = 0; i < header.Cells.Count; i++)
                    {

                        await employee.UpdateEmployeeFromCell(header.Cells[i].StringCellValue, row.Cells[i],
                            async (p) =>
                            {
                                var param = new GetListParams<Employee>();
                                param.filter = p;
                                return (await _coreRep.ListEmployees(param)).ToList();
                            }, async (p) =>
                            {
                                var param = new GetListParams<Department>();
                                param.filter = p;
                                return (await _coreRep.GetDepartments(param)).ToList();
                            });
                    }
                    employee.person.AutoGenerateDisplayName();
                    employee.person.AutoGenerateFullName();
                }
                catch (Exception e)
                {
                    employee.messages.Add(MessageModel.CreateError(e.Message + ". " + e.StackTrace));
                }
                rs.Add(employee);
            });
            return Ok(new ResponseModel(rs));
        }

        [HttpPost]
        [Route("ImportEmployees")]
        public async Task<IActionResult> UploadEmployeeExcel(EmployeeCollectionModel model)
        {
            var entities = model.employees.Select(u => u.ToEmployee());
            var rs = new List<EmployeeErrorableModel>();
            foreach (var item in entities)
            {
                try
                {
                    await _coreRep.UpdateOrAddEmployeeByCode(item, await getCurrentUser());
                    rs.Add(new EmployeeErrorableModel(item));
                }
                catch (Exception e)
                {
                    var irs = new EmployeeErrorableModel(item);
                    irs.messages.Add(MessageModel.CreateError(e.Message + "" + (e.InnerException == null ? "" : e.InnerException.Message) + " " + e.StackTrace));
                    rs.Add(irs);
                }
            }
            return Ok(new ResponseModel(rs));
        }
        #endregion

        #region DEPARTMENT
        [HttpPost]
        [Route("dept/detail/{id}")]
        public async Task<IActionResult> GetDepartment(int id)
        {
            var dept = await _coreRep.GetDepartmentById(id);
            return Ok(new ResponseModel(new DepartmentModel(dept)));
        }

        [HttpPost]
        [Route("depts")]
        public async Task<IActionResult> GetDepartments(TableParameter param)
        {
            var eParam = param.ToEntityParam<Department>();
            eParam.orderBy = u => u.Code;
            var depts = await _coreRep.GetDepartments(eParam);

            var count = await _coreRep.GetDepartmentCount(eParam);
            return Ok(new BaseListModel<DepartmentModel>(depts.Select(u => new DepartmentModel(u)), param.page, param.pageSize, count));
        }

        [HttpPost]
        [Route("dept/update/{id}")]
        public async Task<IActionResult> UpdateDepartment(int id, DepartmentModel model)
        {
            var entity = new Department
            {
                Id = id,
                Code = model.code,
                FullName = model.name,
                ShortName = model.shortname,
                ParentId = model.parentId,
                ManagerId = model.managerId
            };
            await _coreRep.UpdateDepartment(entity, await getCurrentUser());
            return Ok(new ResponseModel(new
            {
                result = true
            }));
        }

        [HttpPost]
        [Route("dept/delete")]
        public async Task<IActionResult> DeleteDepartments(IntCollectionModel model)
        {
            foreach (var id in model.collection)
            {
                await _coreRep.DeleteDepartment(id, await getCurrentUser());
            }
            return Ok(new ResponseModel());
        }

        [HttpPost]
        [Route("deptsselection")]
        public async Task<IActionResult> GetDepartmentsSelection(string search)
        {
            var param = new GetListParams<Department>();
            if (!string.IsNullOrEmpty(search))
                param.extension = query => query.Where(u => u.Code.Contains(search) || u.FullName.Contains(search) || u.ShortName.Contains(search));
            param.orderBy = u => u.Code;
            param.orderDir = GetListParams<Department>.ORDER_DIR_ASC;
            param.page = 0;
            param.pageRows = 100;
            var dept = await _coreRep.GetDepartments(param);
            return Ok(new ResponseModel(dept.Select(u => new
            {
                text = u.FullName,
                value = u.GetId()
            })));
        }

        [HttpPost]
        [Route("ReviewDepartmentExcel")]
        public async Task<IActionResult> ReviewDepartmentExcel()
        {
            var file = Request.Form.Files[0];
            var rs = new List<DepartmentErrorableModel>();
            await FileHelper.scanExcel(file, 6, async (header, row) =>
            {
                var dept = new DepartmentErrorableModel();
                try
                {
                    for (var i = 0; i < header.Cells.Count; i++)
                    {
                        if (row.Cells.Count > i)
                        {
                            await dept.UpdateDepartmentFromCell(header.Cells[i].StringCellValue, row.Cells[i],
                                 async (p) =>
                                 {
                                     var param = new GetListParams<Department>();
                                     param.extension = query => query.Where(u => u.Code == p);
                                     return await _coreRep.GetDepartments(param);
                                 });
                        }
                    }
                }
                catch (Exception e)
                {
                    dept.messages.Add(MessageModel.CreateError(e.Message + " " + e.StackTrace, e.Source));
                }
                rs.Add(dept);
            });
            return Ok(new ResponseModel(rs));
        }

        [HttpPost]
        [Route("ImportDepartments")]
        public async Task<IActionResult> UploadDepartmentExcel(DepartmentCollectionModel model)
        {
            var depts = model.depts;
            var entities = depts.Select(u => u.ToEntity());
            var rs = new List<DepartmentErrorableModel>();
            foreach (var item in entities)
            {
                try
                {
                    await _coreRep.UpdateOrAddDepartmentByCode(item, await getCurrentUser());
                    if (item.ParentId != null)
                        item.Parent = await _coreRep.GetDepartmentById(item.ParentId ?? 0);
                    var irs = new DepartmentErrorableModel(item);
                    rs.Add(irs);
                }
                catch (Exception e)
                {
                    var irs = new DepartmentErrorableModel(item);
                    irs.messages.Add(MessageModel.CreateError(e.Message + " ------" + e.StackTrace));
                    rs.Add(irs);
                }
            }
            return Ok(new ResponseModel(rs));
        }
        #endregion
    }
}